title: danilw.github.io
description: Projects and blogs links.
show_downloads: false
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
